name: Build Application

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Build app for release
        run: msbuild DiskUtilityCLI/DiskUtilityCLI.vcxproj -t:rebuild -verbosity:diag -property:Configuration=Release -property:Platform=x64

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: diskutil.exe
          path: |
            Build/Release-x64/Binraries/diskutil.exe
